### ISSUE TITLE
Can't use connection strings with passwords

### ISSUE THREAD

**Issue by emelent** [brthor/Gofer.NET#45]
I'm struggling to connect to redis when the connection string has a password. How do I specify a password in the connection string?

I tried the following formats to no avail,

`var connString = "redis://<user>:<password>@<host>:<port>";`

`var connString = "<host>:<port>,password=<password>";`

**Comment by brthor** [comment]
From the StackExchange Redis docs it appears the second format you showed is the appropriate one.

https://stackexchange.github.io/StackExchange.Redis/Configuration

You can see we are passing that string directly to the StackExchange.Redis so this doesn't seem to be a Gofer.NET issue if there is a bug here.

https://github.com/brthor/Gofer.NET/blob/master/RedisBackend.cs#L20

I would recommend doing a quick test connecting with StackExchange.Redis directly and determining the issue from there.

**Comment by brthor** [comment]
Perhaps if you shared any errors you are encountering I could offer more insight.

**Comment by emelent** [comment]
Thanks, sorry for the late response. The second connection string does work, I think I had a typo in there.
