### ISSUE TITLE
Simple way to get Queue Depth?

### ISSUE THREAD

**Issue by patricker** [brthor/Gofer.NET#48]
I wanted to add an output showing how many jobs are currently queued, but it doesn't look like queue depth is something that is tracked internally?

**Comment by brthor** [comment]
Indeed it looks that the length of the queue is not exposed.

I can see how this can be useful though. Feel free to make a PR, should be a simple change to the RedisQueue. Perhaps a method called `Length`. It would only need to call the redis `llen` command.

https://github.com/brthor/Gofer.NET/blob/master/RedisQueue.cs#L10

If you're looking for something immediate you could access the redis connection and call `llen` that way.

**Comment by brthor** [comment]
Note this wouldn't get the number of scheduled jobs though.

**Comment by patricker** [comment]
Thanks @brthor I thought it would be easy and wrote it up yesterday. It's working, but I'm having trouble with docker in my environment so I haven't written any test cases so far.

**Comment by patricker** [comment]
I've been testing this for a bit over a week and it appears to be accurate/precise.
https://github.com/brthor/Gofer.NET/pull/49/files

**Comment by patricker** [comment]
Closing out, will let the PR take it from here.
